In [2]:
import numpy as np
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


Aggregate Functions

In [2]:
a.min()

np.int64(1)

In [3]:
a.max()

np.int64(4)

In [4]:
a.sum()

np.int64(10)

In [7]:
a.mean()

np.float64(2.5)

In [10]:
np.median(a)

np.float64(2.5)

AGGREGATE FUNCTIONS ON MULTI-DIMENSIONAL ARRAY

In [3]:
B = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [14]:
B.mean()

np.float64(8.5)

In [4]:
B.mean(axis =0)

array([ 7.,  8.,  9., 10.])

In [16]:
B.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

Creating an array from a list

In [8]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(arr)

[1 2 3 4 5]


Creating an array from multiple lists

In [9]:
row1 = [1, 2, 3]
row2 = [4, 5, 6]
row3 = [7, 8, 9]

arr = np.array([row1, row2, row3])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
col1 = [1, 4, 7]
col2 = [2, 5, 8]
col3 = [3, 6, 9]

arr = np.array([col1, col2, col3]).T
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Creating arrays from a shape or value
Creating an array where all values are  
x

In [12]:
my_value = 5
size = (3, 4)
arr_X = np.full(size, my_value)
print(arr_X)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [13]:
arr_zero = np.zeros(size)
arr_one = np.ones(size)
print(arr_zero)
print(arr_one)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Creating an array full of random numbers

In [14]:
rows = 2
cols = 3
arr_random = np.random.rand(rows, cols)
print(arr_random)

[[0.40020805 0.62730995 0.90705749]
 [0.44698285 0.0470366  0.13111785]]


Creating an array with numbers only on the diagonal

In [15]:
size = 4
diagonal_values = [1, 2, 3, 4]
arr_diagonal = np.diag(diagonal_values)
print(arr_diagonal)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Creating arrays according to a sequence

In [16]:
arr = np.arange(0, 1001, 1)
print(arr)

[   0    1    2 ...  998  999 1000]


In [18]:
arr = np.arange(1001)
print(arr)

[   0    1    2 ...  998  999 1000]


Arrays with a specified data type

In [19]:
arr_int = np.array(my_list, dtype = "int")
print(arr_int)


[1 2 3 4 5]


In [20]:
arr_float = np.array(my_list, dtype = "float")
print(arr_float)

[1. 2. 3. 4. 5.]


In [21]:
arr_zero_int = np.zeros((2,2), dtype = "float")
print(arr_zero_int)

[[0. 0.]
 [0. 0.]]


Modifying values in an array

In [22]:
arr
print(arr)

[   0    1    2 ...  998  999 1000]


In [24]:
arr[0] = -1
print(arr)

[  -1    1    2 ...  998  999 1000]


Array Attributes

In [25]:
arr_a = np.array([[1, 2, 3],[4, 5, 6]])
arr_b = np.array([1.5, 2.7, 3.9])
arr_c = np.array([True,False,True])
print(arr_a)
print(arr_b)
print(arr_c)

[[1 2 3]
 [4 5 6]]
[1.5 2.7 3.9]
[ True False  True]


In [26]:
arr_a.size


6

In [27]:
arr_a.shape

(2, 3)

In [28]:
arr_a.dtype

dtype('int64')

In [29]:
arr_b.size

3

In [30]:
arr_b.shape

(3,)

In [32]:
arr_b.dtype

dtype('float64')

In [33]:
arr_c.size

3

In [34]:
arr_c.shape

(3,)

In [36]:
arr_c.dtype

dtype('bool')

Changing the shape of an array, while keeping the contents

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [3]:
reshaped_arr = arr.reshape(3, 2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
# For example, we can just specify three rows.
arr.reshape(3, -1)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
# Or just specify two columns
arr.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
arr.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

Inverse: Flattening a multi-dimensional array

In [7]:
reshaped_arr = arr.reshape(3, 2)
flattened = reshaped_arr.flatten()
print(flattened)

[1 2 3 4 5 6]


In [8]:
arr.reshape(3,2).flatten()

array([1, 2, 3, 4, 5, 6])

In [9]:
reshaped_arr.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(3, 2)
reshaped_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
arr.shape


(6,)

In [12]:
reshaped_arr[0,0] = -50
reshaped_arr

array([[-50,   2],
       [  3,   4],
       [  5,   6]])

In [13]:
arr

array([-50,   2,   3,   4,   5,   6])

In [14]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
flattened = arr2.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

In [16]:
flattened[0] = -100
flattened

array([-100,    2,    3,    4,    5,    6])

In [17]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
flattened_with_reshape = arr2.reshape(-1)
flattened_with_reshape

array([1, 2, 3, 4, 5, 6])

In [19]:
flattened_with_reshape[0] = -100
flattened_with_reshape

array([-100,    2,    3,    4,    5,    6])

Accessing elements in an array with indexing

In [2]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
arr[1,1]

np.int64(6)

In [4]:
arr[2,3]

np.int64(12)

Slicing

In [5]:
arr[1]

array([5, 6, 7, 8])

In [6]:
arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr[:, 0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [8]:
arr[1, 0:2]

array([5, 6])

Negative indexing

In [9]:
arr[-1]

array([ 9, 10, 11, 12])

In [10]:
arr[-2]

array([5, 6, 7, 8])

In [11]:
arr[:, -1]

array([ 4,  8, 12])

Caution when modifying slices!

In [12]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
my_slice = arr[:, -1]
my_slice

array([ 4,  8, 12])

In [14]:
my_slice[0] = 1000
my_slice

array([1000,    8,   12])

In [15]:
arr

array([[   1,    2,    3, 1000],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

In [16]:
my_slice.base

array([[   1,    2,    3, 1000],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

In [17]:
slice_copy = arr[:, -1].copy()
slice_copy

array([1000,    8,   12])

In [18]:
slice_copy[1] = 0
slice_copy

array([1000,    0,   12])

In [19]:
arr

array([[   1,    2,    3, 1000],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

Indexing with logical operators

In [20]:
arr > 8

array([[False, False, False,  True],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [21]:
arr[arr > 8]

array([1000,    9,   10,   11,   12])

In [22]:
arr[arr>8] = 8
print(arr)

[[1 2 3 8]
 [5 6 7 8]
 [8 8 8 8]]


In [23]:
compound_condition = (arr % 2 == 1) & (arr > 4)
arr[compound_condition]

array([5, 7])

In [24]:
my_subset = arr[arr<4]
my_subset

array([1, 2, 3])

In [27]:
my_subset.base

Sorting vectors

In [28]:
arr = np.random.randint(10,size=14)
arr

array([2, 6, 8, 6, 3, 5, 6, 3, 2, 4, 3, 5, 9, 0], dtype=int32)

In [29]:
arr.sort()
arr

array([0, 2, 2, 3, 3, 3, 4, 5, 5, 6, 6, 6, 8, 9], dtype=int32)

In [30]:
# Let's make a new randomly generated array to practice on.
arr_b = np.random.randint(10, size =12)
arr_b

array([2, 2, 7, 7, 2, 2, 0, 4, 3, 0, 1, 9], dtype=int32)

In [31]:
sorted_arr_b = np.sort(arr_b)
sorted_arr_b

array([0, 0, 1, 2, 2, 2, 2, 3, 4, 7, 7, 9], dtype=int32)

In [32]:
arr_b

array([2, 2, 7, 7, 2, 2, 0, 4, 3, 0, 1, 9], dtype=int32)

In [36]:
np.flip(np.sort(arr_b))

array([9, 7, 7, 4, 3, 2, 2, 2, 2, 1, 0, 0], dtype=int32)

In [37]:
sorted_arr_b[::-1]

array([9, 7, 7, 4, 3, 2, 2, 2, 2, 1, 0, 0], dtype=int32)

Sorting matrices

In [38]:
matrix_a = np.random.randint(10,size = (4,4))
matrix_a

array([[9, 4, 2, 1],
       [2, 4, 0, 3],
       [9, 8, 1, 5],
       [0, 0, 3, 2]], dtype=int32)

In [39]:
matrix_a_sort_default = np.sort(matrix_a)
matrix_a_sort_default


array([[1, 2, 4, 9],
       [0, 2, 3, 4],
       [1, 5, 8, 9],
       [0, 0, 2, 3]], dtype=int32)

In [40]:
# same as default
matrix_a_sort_axis = np.sort(matrix_a, axis =  -1)
matrix_a_sort_axis

array([[1, 2, 4, 9],
       [0, 2, 3, 4],
       [1, 5, 8, 9],
       [0, 0, 2, 3]], dtype=int32)

In [41]:
# sort "along" the rows, meaning hold the column fixed and sort the values from the different rows (i.e., sort within each column)
matrix_a_sort_axis = np.sort(matrix_a, axis = 0)
matrix_a_sort_axis

array([[0, 0, 0, 1],
       [2, 4, 1, 2],
       [9, 4, 2, 3],
       [9, 8, 3, 5]], dtype=int32)

Sometimes, we are missing data! This happens a lot when we're collecting data. It's important to represent this clearly in our data. One way to do this is with a "NaN"- short for "not a number". numpy has a special way of representing this. Let's work with an example.

In [44]:
arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])
print(arr)

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [45]:
np.isnan(arr)

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])

Counting NaN values

In [46]:
np.count_nonzero(np.isnan(arr))

np.int64(2)

In [47]:
np.isnan(arr).sum()

np.int64(2)

Working with NaN values

In [48]:
arr.sum()

np.float64(nan)

In [49]:
np.nansum(arr)

np.float64(37.0)

In [51]:
arr[np.isnan(arr)] = 0

In [52]:
np.where(np.isnan(arr), 0, arr)

array([[1., 2., 0.],
       [4., 0., 6.],
       [7., 8., 9.]])

Joining arrays

In [53]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [54]:
arr1

array([1, 2, 3])

In [55]:
arr2

array([4, 5, 6])

In [56]:
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [57]:
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [58]:
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

In [60]:
arr3

array([[1, 2],
       [3, 4]])

In [61]:
arr4

array([[5, 6],
       [7, 8]])

In [62]:
np.concatenate((arr3, arr4))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [63]:
np.concatenate((arr3, arr4), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
np.vstack((arr3, arr4))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:

np.hstack((arr3, arr4))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [66]:
arr4 = np.array([[5, 6], [7, 8]])

In [67]:
arr5 = np.array([9,10])

In [68]:
np.vstack((arr4, arr5))

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Arithmetic
Addition

In [72]:
arr_a = np.array([1, 2, 3, 4, 5])
arr_b = np.array([6, 7, 8, 9, 10])
arr_a + arr_b

array([ 7,  9, 11, 13, 15])

In [73]:
np.add(arr_a,arr_b)

array([ 7,  9, 11, 13, 15])

Subtraction

In [74]:
arr_a - arr_b

array([-5, -5, -5, -5, -5])

In [76]:
 np.subtract(arr_a, arr_b)

array([-5, -5, -5, -5, -5])

Multiplication

In [77]:
arr_a * arr_b

array([ 6, 14, 24, 36, 50])

In [78]:
np.multiply(arr_a, arr_b)

array([ 6, 14, 24, 36, 50])

Division

In [79]:
arr_a/arr_b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [80]:
np.divide(arr_a, arr_b)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

Logical operations

In [81]:
arr_a > 3

array([False, False, False,  True,  True])

In [82]:
np.any(arr_a > 3)

np.True_

In [83]:
np.all(arr_a > 3)

np.False_

In [84]:
arr_c = np.array([True, True, False, True])
arr_d = np.array([True, False, True, True])

In [85]:
arr_c & arr_d

array([ True, False, False,  True])