In [3]:
import numpy as np

In [2]:
print(np.__version__)

2.3.5


In [ ]:
# 1.creating array!

In [1]:
l1 = [1,2,3]
print(l1)

[1, 2, 3]


In [4]:
array_1 = np.array(l1)
print(array_1)

[1 2 3]


In [6]:
print(type(array_1))

<class 'numpy.ndarray'>


In [7]:
l1 = [1,2,3]
l2 = [4,5,6]
array2 = np.array ([l1,l2])
print(array2)

[[1 2 3]
 [4 5 6]]


In [10]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]
array3 = np.array ([[l1,l2,l3]])
print(array3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [11]:
print(array3.ndim)

3


In [12]:
print(array2.ndim)

2


In [13]:
print(array_1.ndim)

1


In [ ]:
#2. numpy array attributes

In [17]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [19]:
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


In [ ]:
#3. Array initialization methods

In [20]:
#zeros array
zerosarr1 = np.zeros((2,3))
print(zerosarr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
#ones array
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#full array
full = np.full((2,3) ,9)
print(full)

[[9 9 9]
 [9 9 9]]


In [23]:
#identity metrix
idmatrix = np.eye(3)
print(idmatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
#empty array
print(np.empty(2))

[0.00000000e+000 1.35899497e-311]


In [25]:
#evenly spaced array
print(np.arange(1,10,2))

[1 3 5 7 9]


In [26]:
#specific number of values between a range
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [27]:
#random values array float
rand_array = np.random.rand(3,3)
print(rand_array)

[[0.11135701 0.62084906 0.97540807]
 [0.15669061 0.15755638 0.09272895]
 [0.44058848 0.63291807 0.31562875]]


In [1]:
#random values array int
import numpy as np
rand_array = np.random.randint(3,100,(3,3))
print(rand_array)

[[55 63 56]
 [40 10 89]
 [77 96 87]]


In [2]:
#array indexing and slicing.
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
print(a[0])

1


In [4]:
print(a[-1])

5


In [ ]:
#slicing
#array = [start,stop,step]

In [3]:
a = np.array([5,6,7,8,9])
print(a[0:3])

[5 6 7]


In [5]:
print(a[-3:-1])

[7 8]


In [6]:
print(a[0::2])

[5 7 9]


In [7]:
arr2 = np.array ([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
print(arr2[0])

[1 2 3]


In [9]:
print(arr2[1])

[4 5 6]


In [10]:
print(arr2[0][0])

1


In [11]:
print(arr2[1][2])

6


In [12]:
print(arr2[1:])

[[4 5 6]]


In [13]:
print(arr2[:,2])

[3 6]


In [ ]:
#2D : rows and columns
#3D : height/layers, rows and cloumns

In [17]:
arr3 = np.array ([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(arr3.ndim)

2


In [22]:
print(arr3[0])

[1 2 3]


In [23]:
print(arr3[0][1])

2


In [25]:
print(arr3[:,1])

[2 5 8]


In [26]:
print(arr3[:,2])

[3 6 9]


In [29]:
print(arr3[::2,0])

[1 7]


In [ ]:
#Array reshaping and flattening

In [30]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [33]:
reshaped = arr.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [34]:
print(reshaped.ndim)

2


In [36]:
reshaped2 = arr.reshape((2,3))
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [38]:
print(reshaped2.flatten())

[1 2 3 4 5 6]


In [43]:
#array stacking and splitting
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [63]:
c = np.array([[1,2,3],
            [4,5,6]])
print(c)
print(c.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [46]:
split = np.hsplit(c,3) 
for s in split:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [48]:
split = np.vsplit(c,2) 
for s in split:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [ ]:
#mathematical operations on array

In [50]:
a = np.array([10,20,30,40,-30])
print(a)

[ 10  20  30  40 -30]


In [51]:
print(a+10)

[ 20  30  40  50 -20]


In [52]:
print(a-10)

[  0  10  20  30 -40]


In [53]:
print(a/2)

[  5.  10.  15.  20. -15.]


In [54]:
print(a*12)

[ 120  240  360  480 -360]


In [56]:
b = np.array([1,4,9])
b

array([1, 4, 9])

In [57]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


In [58]:
#mathematical operations on multiple array
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [60]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [61]:
print(np.dot(a,b))

32


In [62]:
print(a.T) #transpose

[1 2 3]


In [ ]:
#statistical Functions

In [64]:
c = np.array([[1,2,3],
            [4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [66]:
print(np.sum(c))
print(np.mean(c))
print(np.median(c))
print(np.var(c))
print(np.std(c))

21
3.5
3.5
2.9166666666666665
1.707825127659933


In [67]:
#array comparison
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)


[1 2 3]
[4 5 6]


In [68]:
print(a==b)

[False False False]


In [70]:
#broadcasting
a = np.array([1,2,3,4,5])
b = np.array([2])
print(a+b)

[3 4 5 6 7]


In [72]:
#handling with nan values
data = np.array([np.nan,1,2,3,np.inf])
print(data)

[nan  1.  2.  3. inf]


In [73]:
print(np.isnan(data))

[ True False False False False]


In [74]:
print(np.nan_to_num(data))

[0.00000000e+000 1.00000000e+000 2.00000000e+000 3.00000000e+000
 1.79769313e+308]


In [76]:
#save and load array
arr = np.array([1,2,3])
print(arr)
np.save('mi_array.npy',arr)

[1 2 3]
